article:
    path:     /
    defaults: { _controller: "OSEFAppBundle:Article:index" }

article_new:
    path:     /new
    defaults: { _controller: "OSEFAppBundle:Article:new" }
    requirements: { _method: get|post }

article_show:
    path:     /{slug}
    defaults: { _controller: "OSEFAppBundle:Article:show" }

article_edit:
    path:     /{id}/edit
    defaults: { _controller: "OSEFAppBundle:Article:edit" }
    requirements: { _method: get|post|put }

article_delete:
    path:     /{id}/delete
    defaults: { _controller: "OSEFAppBundle:Article:delete" }
    requirements: { _method: post|delete }
